#!/usr/bin/env zsh

export MLIS_LOCATION="~/Documents/src/ezaddon-mlis"
export KUBECONFIG="~/Documents/src/ezdeployer/ua/tooling/scripts/worker_kubeconfig"
export VENV_DIR="~/Documents/.virtualenvs/mlis"

pushd $MLIS_LOCATION

source $VENV_DIR/bin/activate

make aie-delete
kubectl delete pvc -n mlis aioli-db-pvc-hpe-mlis --kubeconfig $KUBECONFIG
make install
make release-local
make aie-install

deactivate

popd
