#!/usr/bin/env zsh

export MLIS_LOCATION="~/Documents/src/ezaddon-mlis"
export KUBECONFIG="~/Documents/src/ezdeployer/ua/tooling/scripts/worker_kubeconfig"
export VENV_DIR="~/.virtualenvs/mlis"
export AWS_SECRET_ACCESS_KEY="admin123"
export AWS_ENDPOINT_URL="http://10.227.210.150:9000"
export AWS_ACCESS_KEY_ID="admin"
export AIEUSER="thomas-kelley"
export AIOLI_CONTROLLER="https://mlis.10.227.212.49.nip.io/"
export HF_TOKEN=$(cat ~/.api-keys/hf_token)

echo "###############################################################################"
echo "Entering MLIS Location: $MLIS_LOCATION"
echo "###############################################################################"
echo

pushd $MLIS_LOCATION

echo
echo "###############################################################################"
echo "Initializing Python Interpreter at $VENV_DIR"
echo "###############################################################################"
echo

source $VENV_DIR/bin/activate
pip install boto3

echo
echo "###############################################################################"
echo "Cleaning the current context"
echo "###############################################################################"
echo

make clean

echo
echo "###############################################################################"
echo "Staging data to MinIO"
echo "###############################################################################"
echo

make -C test stage

echo
echo "###############################################################################"
echo "Running e2etests"
echo "###############################################################################"
echo

make e2etest
E2ETESTRESULT="$?"

echo
echo "###############################################################################"
echo "Exiting Python Interpreter"
echo "###############################################################################"
echo

deactivate

echo "###############################################################################"
echo "Leaving MLIS Location"
echo "###############################################################################"

popd

exit $E2ETESTRESULT
