#!/usr/bin/env zsh

function wait_for_vm_ping() {
    SLEEP_TIME=1
    until ping -c 1 -W 5000 $1 > /dev/null ; do
        echo "Waiting for pingback from $1..." ;
        sleep $SLEEP_TIME
        SLEEP_TIME=$((SLEEP_TIME + SLEEP_TIME))
    done
}

function wait_for_vm_ssh() {
    SLEEP_TIME=1
    until sshexp $1 "exit 0" ; do
        echo "Waiting for ssh to $1..." ;
        sleep $SLEEP_TIME
        SLEEP_TIME=$((SLEEP_TIME + SLEEP_TIME))
    done
}

VM_LIST=("10.227.210.149" "10.227.210.150" "10.227.212.38" "10.227.212.49" "10.227.212.51")

for VM in "${VM_LIST[@]}"; do
    wait_for_vm_ping "$VM" ;
    wait_for_vm_ssh "$VM" ;
done
